# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Checkout git submodules
      run:  |
            git submodule sync 
            git submodule update --init
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install OS Dependencies
      run:  |
            if [ "$RUNNER_OS" == "Linux" ]; then
                  sudo apt-get install libgtk-3-dev xvfb at-spi2-core
            fi
      shell: bash
    - name: Build
      run:  npm ci
    - name: Run tests 
      if:   matrix.os == 'ubuntu-latest'
      run:  |
            export DISPLAY=':99.0'
            Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
            npm test
    - name: Run tests
      if:   matrix.os != 'ubuntu-latest'
      run:  npm test
    - name: Archive test artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-picture-example-window
        path: win.png
