# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run:  |
            if [ "$RUNNER_OS" == "Linux" ]; then
                  sudo apt-get install libgtk-3-dev
            elif [ "$RUNNER_OS" == "Windows" ]; then
                  echo choco install important_windows_software
            else
                  echo "$RUNNER_OS"
            fi
      shell: bash
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
